### ISSUE TITLE
libsharp2 performance

### ISSUE THREAD

**Issue by damonge** [LSSTDESC/NaMaster#122]
When switching to libsharp2 (in #121 ), I did not observe any noticeable improvement in performance. This should be investigated.

**Comment by mreineck** [comment]
Since you were using the "batch" mode of the old libsharp (as fas as I can tell), which was removed in libsharp2, it's quite possible that the loss of this mode and the gain due to the new SHT algorithm cancel themselves more or less.
If you see no speedup even for single transforms, that should indeed be investigated further.

**Comment by damonge** [comment]
Thanks @mreineck , will do.
My suspicion is that this may be due to my very outdated gcc, but I'll get back to this.

**Comment by ickc** [comment]
Hi, related to libsharp/libsharp2 and their performance, are there any plans to switch to ducc0? Thanks.

**Comment by mreineck** [comment]
That would imply compiling at least a part of NaMaster with a C++ compiler, since ducc0 doesn't have a plain C interface (yet). 
Not that this is a bad thing, but I wanted to point it out.

(You could then also use ducco's new Wigner 3j symbols - they should be about 40% faster than those in NaMaster :-)

**Comment by mreineck** [comment]
Sorry, I just realized that NaMaster _is_ actually written in C++, despite the filename extensions ...

**Comment by damonge** [comment]
I have been planning to move to ducc0, but was dragging my feet (and waiting to check it was stable!), so this is a good poke.

If/when that happens, my plan was to move most of the code base to python and use the python interface for anything SHT related. Thoughts are very welcome!

**Comment by mreineck** [comment]
My feeling is that ducc0 is at least as stable as libsharp2, so that shouldn't be an issue. Sorry for still sticking to 0.x version numbers ... I wanted to switch as soon as I have to break backwards compatibility for some reason, but that hasn't happened so far, to my own surprise.

Moving most of the code base to Python sounds great (especially the bits that revolve around I/O; this gives a lot more flexibility with data formats etc.), but there seem to be quite a few functions that are really performance critical. Perhaps I can help by adding support for mode coupling matrices to ducc (@xzackli suggested this); but would that be sufficient?

**Comment by mreineck** [comment]
This is getting more and more off-topic, but still...
I have now found a way to compute Wigner 3j elements roughly three times as quickly as the implementation in Namaster ... but there is a catch: you always have to compute four combinations of l2 and l3 together, so this not fully compatible with the existing NaMaster loop structure.
If you are interested in this, I'd be happy to help with integration.

**Comment by damonge** [comment]
Definitely sounds interesting. It'd be great to know more about it and try to implement it! Happy to chat offline.

**Comment by damonge** [comment]
Migrated to ducc0, so not relevant anymore.
