### ISSUE TITLE
Pseudo-cl's in the covariance computation - pixel window function 

### ISSUE THREAD

**Issue by olakusiak** [LSSTDESC/NaMaster#198]
Hi Namaster team, 

I am wondering about the proper treatment of the theory cl’s that go into the covariance computation. If I don’t have any theory power spectra, so I follow the Nicola et al. treatment and the [Note](https://namaster.readthedocs.io/en/latest/api/pymaster.covariance.html#pymaster.covariance.gaussian_covariance) in the documentation, and I compute the “pseudo-𝐶ℓ
 of the associated maps (e.g. computed via compute_coupled_cell()), divided by the same mean mask product”. 
 
 However, I am wondering if these pseudo-Cl ’s should in principle be corrected for the pixel window function if they are supposed to represent the “true” power spectra ?
I tested it, and this is a small effect for nside=4096, but I was wondering what the correct treatment is. Thank you! 
![download-6](https://github.com/LSSTDESC/NaMaster/assets/62485729/488ddfec-6ae2-4558-8fa9-325f71c9e030)

**Comment by damonge** [comment]
Hi Ola!

no, in this case, since you are computing the pCl that enters the covariance from your own data, you should not correct the result for the pixwin. I am assuming here that, if your data is affected by a pixwin, you will have either passed that pixwin as the `beam` argument of the corresponding NmtFields, in which case any pixwin deconvolution is taken care of automatically by the corresponding workspaces (optionally, you may be forward-modelling the pixwin in your theoretical prediction, if these C_ells are being used in a likelihood, but in that case you should also not correct the covariance pCls for the pixwin).

To clarify more (hopefully), if you were using a theoretical prediction for the C_ell, instead of your own data, you would need to apply a pixwin to that one before mode-coupling, since this C_ell is meant to contain all the effects that are present in your data.

Does this make sense?

**Comment by olakusiak** [comment]
Hi David, thank you for your response! 
Yes, I now add the pixwin as a beam to the corresponding NmtFields (something together with an actual beam), so in this case, if I understand, correctly I never have to worry about the pixwin again (including in the pCl calculation from the same Nmtfields for iNKA for the cov)? 

I think it would be super useful to clarify what is meant by the ‘Cl_theory’  in the covariance documentation (that these might need to include the pixwin/beam depending on one’s assumption, whereas I would normally assume that Cl_theory is a theoretical model for the underlying signal)

**Comment by damonge** [comment]
OK, noted. Luckily we're in the middle of a mild documentation refurbish, so this is good timing ;-)
