### ISSUE TITLE
Computing power spectrum of already masked map

### ISSUE THREAD

**Issue by umilta** [LSSTDESC/NaMaster#91]
I need to compute the power spectrum of an already masked map, of which I have the apodized mask. If I just follow the examples, my map will be multiplied by the mask again and the final power spectrum will not be correct.  

I adapted my script from the existing examples, but I could not confirm from the source code whether or not this makes sense. Given that `my_map` is masked with `apodized_mask`, whose binary version is `binary_mask`, and `other_map` is an unrelated map, is it correct to:
`f_other = nmt.NmtField(apodized_mask, other_map)`
`w = nmt.NmtWorkspace()`
`w.compute_coupling_matrix(f_other, f_other, b)`
`f0 = nmt.NmtField(binary_mask, my_map)`
`cl = nmt.compute_coupled_cell(f0, f0)`
`cl_decoupled = w.decouple_cell(cl)`

Thanks

**Comment by damonge** [comment]
Hi @umilta 
I think what you're doing should work. The main thing to remember is that, when one calls `w.compute_coupling_matrix`, the two fields one passes should have their true masks associated with them. 
Note however, that if you try to use the systematics deprojection or purification functionality in NaMaster, it won't really work for `f0`, since these functions also need to know the mask.

To make things slightly less hackish, I'd do the following:
```
f_other = nmt.NmtField(apodized_mask, other_map)
w = nmt.NmtWorkspace()
# Divide by mask where it's not zero
map_unmasked = np.zeros_like(my_map)
map_unmasked[binary_mask>0.001] = my_map[binary_mask>0.001] / apodized_mask[binary_mask>0.001]
f0 = nmt.NmtField(apodized_mask, map_unmasked)
cl_decoupled = w.decouple_cell(nmt.compute_coupled_cell(f0, f0))
```

I agree that it'd be nice to be able to pass masked maps to NaMaster, so I'll open an issue to address that. Thanks!

**Comment by damonge** [comment]
@umilta this feature has now been implemented in the master branch.

**Comment by umilta** [comment]
Thanks!
